### ISSUE TITLE
Compilation error in Current

### ISSUE THREAD

**Issue by xexpanderx** [CinnamonSlackBuilds/csb#38]
```

/usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
 void     g_type_class_add_private       (gpointer                    g_class,
          ^~~~~~~~~~~~~~~~~~~~~~~~
  CXX      libgjs-private/libcjs_la-gjs-util.lo
  CC       libgjs-private/libcjs_la-gjs-gtk-util.lo
  CXX      modules/libconsole_la-console.lo
  CXXLD    libconsole.la
  CXX      modules/libsystem_la-system.lo
  CXXLD    libsystem.la
  GEN      modules-resources.c
  CC       libmodules_resources_la-modules-resources.lo
  CCLD     libmodules_resources.la
  CXX      modules/libcairoNative_la-cairo-region.lo
  CXX      modules/libcairoNative_la-cairo-context.lo
  CXX      modules/libcairoNative_la-cairo-path.lo
  CXX      modules/libcairoNative_la-cairo-surface.lo
  CXX      modules/libcairoNative_la-cairo-image-surface.lo
  CXX      modules/libcairoNative_la-cairo-ps-surface.lo
  CXX      modules/libcairoNative_la-cairo-pdf-surface.lo
  CXX      modules/libcairoNative_la-cairo-svg-surface.lo
  CXX      modules/libcairoNative_la-cairo-pattern.lo
  CXX      modules/libcairoNative_la-cairo-gradient.lo
  CXX      modules/libcairoNative_la-cairo-linear-gradient.lo
  CXX      modules/libcairoNative_la-cairo-radial-gradient.lo
  CXX      modules/libcairoNative_la-cairo-surface-pattern.lo
  CXX      modules/libcairoNative_la-cairo-solid-pattern.lo
  CXX      modules/libcairoNative_la-cairo.lo
  CXXLD    libcairoNative.la
  CXXLD    libcjs.la
  CXXLD    cjs-console
  CC       installed-tests/libregress_la-regress.lo
  CCLD     libregress.la
  GISCAN   Regress-1.0.gir
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 95, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 42, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "/usr/lib/gobject-introspection/giscanner/dumper.py", line 33, in <module>
    from .gdumpparser import IntrospectionBinary
  File "/usr/lib/gobject-introspection/giscanner/gdumpparser.py", line 35, in <module>
    from .transformer import TransformerException
  File "/usr/lib/gobject-introspection/giscanner/transformer.py", line 35, in <module>
    from .sourcescanner import (
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 38, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ImportError: /usr/lib/gobject-introspection/giscanner/_giscanner.so: wrong ELF class: ELFCLASS32
make[1]: *** [Makefile:3627: Regress-1.0.gir] Error 1
make[1]: Leaving directory '/tmp/csb/cjs-4.0.0'
make: *** [Makefile:1462: all] Error 2
```

**Comment by willysr** [comment]
tested on clean VM and it works fine here

**Comment by willysr** [comment]
Not in multilib, since there's a bug in gobject-introspection : https://gitlab.gnome.org/GNOME/gobject-introspection/issues/220

**Comment by xexpanderx** [comment]
It is because I use multilib, it is pointing on 32 bit libraries. It is a known issue, there is a thread about it on linuxquestion, im on phone now. Will be back.

**Comment by xexpanderx** [comment]
Yes, exactly! A bug in gobject-introspection.

**Comment by willysr** [comment]
gobject-introspection is now bumped to 1.60.0, which should fixed this issue
please confirm after you upgrade to the new version

**Comment by xexpanderx** [comment]
Yes, it works. But other issues appeared, opening a new issue.
